services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    container_name: MovieScheduleApp-dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
  
  webserver:
    image: nginx:mainline-alpine3.20-slim
    container_name: MovieScheduleApp-nginx
    depends_on:
      - backend
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
